name: Patrick Gombert

aboutPage: true

exclude: ["Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

highlighter: rouge

paginate: 20
baseurl: "/"
url: "https://patrickgombert.com"

permalink:       /:year/:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
